# Generated by Django 3.2.3 on 2021-06-02 18:13

from django.db import migrations, models
import sales_manager.shortcut


class Migration(migrations.Migration):

    dependencies = [
        ('sales_manager', '0008_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=sales_manager.shortcut.upload_to),
        ),
    ]
